name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  github-token:
    description: "Your Github token, it's already available to your Github action."
    required: false
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'index.js'
