name: 'Github action label pull request'
description: 'Add label from issues to the pull request'
inputs:
  github-token:
    description: "Your Github token, it's already available to your Github action."
    required: false
    default: ${{ github.token }}
  clean-before-fetching:
    description: "If true all the label will be removed before fetching those from PR"
    required: false
    default: false
  excluded-labels:
    description: "list of comma separated labels that are not added to PR"
    required: false
runs:
  using: 'node20'
  main: 'index.js'
