name: 'Github action label pull request'
description: 'Add label from issues to the pull request'
icon: activity
inputs:
  github-token:
    description: "Your Github token, it's already available to your Github action."
    required: false
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'index.js'
